spring:
  application:
    name: consumer-factura
  cloud:
    config:
      uri: http://localhost:8888

# Activo el perfil default para que obtenga la configuraci√≥n del Config Server
profiles:
  active: default