spring:
  application:
    name: consultador-historialMedico
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_SERVER_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

# Activo el perfil default para que obtenga la configuraci√≥n del Config server
profiles:
  active: default
